### PR TITLE
use pkg-config to find tree sitter include and libs.

### PR DESCRIPTION
**Pull request by diasbruno**

### CODE REVIEW

**Comment by death** [comment]
Hey diasbruno,

I can see a theoretical reason for this change, but would be interested in the actual reason that led to it. Currently a particular tree-sitter header file `api.h` is bundled with cl-tree-sitter and is used when compiling the wrapper. If your change is to be complete, the `tree_sitter/api.h` header from the installed tree-sitter package needs to be included instead. In effect this change makes the wrapper's shared object explicitly dependent on tree-sitter's shared object. Since cl-tree-sitter loads both objects in the correct order, as far as I can tell, and assuming the wrapper is not used by anything else, I'm not aware of any practical difference. Of course, if tree-sitter changes its ABI, then automatically including the most up-to-date header is advantageous. Probably @berchn would be interested in this discussion.

**Comment by diasbruno** [comment]
In my case, I'm using nix, but I added because `cffi-libffi` (I don't remember) also uses `pkg-config`...

**Comment by diasbruno** [comment]
Or maybe check for `pkg-config` (before use it) instead of making it a dependency (?)

**Comment by diasbruno** [comment]
Here is the log of the compilation without the libraries:

```sh
make
cc -g -O2 -Wall -Wno-unused-value -fPIC -shared   tree-sitter-wrapper.c -o tree-sitter-wrapper.so
Undefined symbols for architecture arm64:
  "_ts_node_end_point", referenced from:
      _ts_node_end_point_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_node_end_point_pointer)
  "_ts_node_is_named", referenced from:
      _ts_node_is_named_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_node_is_named_pointer)
  "_ts_node_start_point", referenced from:
      _ts_node_start_point_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_node_start_point_pointer)
  "_ts_node_type", referenced from:
      _ts_node_type_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_node_type_pointer)
  "_ts_tree_cursor_current_node", referenced from:
      _ts_tree_cursor_current_node_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_tree_cursor_current_node_pointer)
  "_ts_tree_cursor_new", referenced from:
      _ts_tree_cursor_new_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_tree_cursor_new_pointer)
  "_ts_tree_root_node", referenced from:
      _ts_tree_root_node_pointer in tree-sitter-wrapper-b63c21.o
     (maybe you meant: _ts_tree_root_node_pointer)
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:15: tree-sitter-wrapper.so] Error 1
```

**Comment by ruricolist** [comment]
If we change `#include "api.h"` to `#include <tree_sitter/api.h>`, move api.h into a `tree_sitter` subdirectory, and pass `-I.` as the last arg in `CFLAGS`, that would handle using the most up to date header if available, falling back to the one provided.

For portability `which` should also be `command -v`.

**Comment by diasbruno** [comment]
The suggestions were great, @ruricolist. But one things is still missing...the libraries needs to be found somewhere.
I don't know if adding tree-sitter as a submodule would help, or, delegate to the user to install the tree-sitter and provide the right location of the libraries would be better.

**Comment by death** [comment]
Hopefully I will be merging this soon. I would also accept a patch removing `api.h` from cl-tree-sitter, if the folks using it agree with such a decision.

**Comment by ruricolist** [comment]
I don't know if you can use pkg-config with the Quicklisp build environment.

**Comment by diasbruno** [comment]
I removed the tree-sitter's files for now and make it such that the user can also define the variables in case they are in another location (and pkg-config been used by default).

Tested with 0.20.8 (latest tag from homebrew).

**Pull request merged**
